[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "lxml>=6.0.0",
    "openai>=1.99.5",
    "tiktoken>=0.11.0",
]
